name: Build and Deploy

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install setup tools
      run: sudo apt-get install -y python3-setuptools

    - name: Install requirements
      run: pip3 install -r server/requirements.txt

    - name: Run tests
      run: |
        cd server
        python3 test_drawing.py

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install setup tools
      run: sudo apt-get install -y python3-setuptools

    - name: Install requirements
      run: pip3 install -r server/requirements.txt

    - name: Override config file
      run: |
        cd server
        rm config.json
        echo ${{ secrets.CONFIG_BASE64 }} | base64 --decode > config.json

    - name: Authenticate gcloud service account
      run: |
        cd server
        gcloud config set project subwaydisplay
        gcloud config set account subway-service-account@subwaydisplay.iam.gserviceaccount.com
        echo ${{ secrets.GCLOUD_API_BASE64 }} | base64 --decode > gcloud.json
        gcloud auth activate-service-account --key-file=gcloud.json --project=subwaydisplay

    - name: Upload kindle file to gcloud
      run: |
        gsutil cp kindle/refresh_display.sh gs://subwaykindledisplay/
        gsutil acl ch -u AllUsers:R gs://subwaykindledisplay/refresh_display.sh

    - name: Submit build to Google Cloud
      run: |
        cd server
        gcloud builds submit --tag gcr.io/subwaydisplay/helloworld

    - name: Log to discord
      run: apprise -vv -b "Deploying new version to Google Cloud Run" "discord://$DISCORD_WEBHOOK_ID/$DISCORD_WEBHOOK_TOKEN/?avatar=No"
      env:
        DISCORD_WEBHOOK_ID: ${{ secrets.DISCORD_WEBHOOK_ID }}
        DISCORD_WEBHOOK_TOKEN: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}

    - name: Deploy to Google Cloud Run
      run: |
        cd server
        gcloud beta run deploy helloworld --image gcr.io/subwaydisplay/helloworld --platform managed --allow-unauthenticated --region us-east1
